version: "3"
services:
  server:
    container_name: server
    build: ./core
    ports:
      - 5000:5000
    develop:
      watch:
        - path: ./core/requirements.txt
          action: rebuild
        - path: ./core
          target: /core
          action: sync
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client/next.config.js
          action: rebuild
        - path: ./client
          target: /client
          action: sync
    depends_on:
      - server
