version: "3"
services:
  server:
    container_name: server
    build: ./core
    ports:
      - 5000:5000
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - server
