name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      env:
        VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
        VPS_IP: ${{ secrets.VPS_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
          cd /home/ubuntu/WebQAFinalKL
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF
